# Args: <obj_file> <output_dir>
{
  "version": 3,
  "setup": {
    #"blender_install_path": "/home/theodore/Development/BlenderProc/blender/",
    "blender_install_path": "/home/ttsesm/Development/BlenderProc/blender/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {
        "global": {
#          "output_dir": "examples/suncg_with_vi_suite/output"
          "output_dir": "<args:1>"
        }
      }
    },
    {
      "module": "manipulators.WorldManipulator",
      "config": {
        "cf_bg_surface_color": [ 1, 1, 1, 1 ],
        "cf_bg_surface_strength": 100
      }
    },
    {
      "module": "loader.SuncgLoader",
      "config": {
        #"path": "/home/theodore/Development/datasets/suncg/house/001ef7e63573bd8fecf933f10fa4491b/house.json"
#        "path": "/home/ttsesm/Development/datasets/suncg/house/001ef7e63573bd8fecf933f10fa4491b/house.json"
        "path": "<args:0>"
      }
    },
    {
      "module": "lighting.SuncgLighting",
    }
  ]
}
